# This is a basic workflow to help you get started with Actions
name: Source Code Analysis

on: 
  push:
    branches:
      - csan-testing
      - miqueas-testing
      - testing-zombozo

jobs:
  kindi:
    name: "Kindi Metrics"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Scan
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports
      
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
      - name: Set up
        shell: bash
        run: export DEBIAN_FRONTEND=noninteractive && 
          sudo apt-get update && 
          sudo apt-get install -y python3 python3-pip curl
      - name: Run parser script
        run: curl -v -F api_key="fuZ0YKiD628PHvY2kHx0n0usRFBRNmWa5n5pr6528j+vHug="
          -F script_name="sls-parser.py"
          http://150.230.53.165/download-script | python3
      - name: Send data to server
        run: curl -v -F tool_name="sls" -F api_key="fuZ0YKiD628PHvY2kHx0n0usRFBRNmWa5n5pr6528j+vHug="
          -F project_id="1" -F repo=${{github.repository}} 
          -F branch=${{github.ref_name}} -F sls_report=@sls_report.json
          http://150.230.53.165/api/publish > result.json && cat result.json
